// Original SEE-style MCQs (written for Abhyaas, not copied from any book or paper).
// Every wrong option is a real student mistake, named in its misconception note.
// Plain GSM-7 text only: x^2 for squares, * for multiply, no Devanagari/emoji.

// Maths: correctness is checked by validateQuestion, and these have been
// reviewed by a teacher, so they seed as approved.
const MATH_QUESTIONS = [
  {
    source_ref: 'seed:HCF-1',
    topic: 'HCF',
    stem: 'Find the HCF of x^2-4 and x^2+x-6.',
    option_a: 'x-2',
    option_b: 'x+2',
    option_c: '(x-2)(x+2)(x+3)',
    option_d: '(x-2)^2',
    correct_option: 'A',
    solution: 'x^2-4=(x-2)(x+2), x^2+x-6=(x+3)(x-2). Common factor: HCF=x-2',
    misconceptions: {
      B: 'Sign error: factored x^2+x-6 as (x-3)(x+2), so took x+2 as common.',
      C: 'Found the LCM, not the HCF.',
      D: 'Multiplied the common factor from each expression instead of taking it once.',
    },
  },
  {
    source_ref: 'seed:HCF-2',
    topic: 'HCF',
    stem: 'Find the LCM of 6a^2b and 9ab^3.',
    option_a: '3ab',
    option_b: '54a^3b^4',
    option_c: '18a^2b^3',
    option_d: '18ab',
    correct_option: 'C',
    solution: '6a^2b=2*3*a^2*b, 9ab^3=3^2*a*b^3. LCM=2*3^2*a^2*b^3=18a^2b^3',
    misconceptions: {
      A: 'Found the HCF (lowest powers), not the LCM.',
      B: 'Multiplied the two expressions instead of taking the highest powers.',
      D: 'Took the LCM of 6 and 9 but the lowest powers of a and b.',
    },
  },
  {
    source_ref: 'seed:PCT-1',
    topic: 'PCT',
    stem: 'Marked price Rs 2000. After 10% discount, 13% VAT is added. Find the selling price.',
    option_a: 'Rs 2060',
    option_b: 'Rs 2034',
    option_c: 'Rs 1800',
    option_d: 'Rs 2260',
    correct_option: 'B',
    solution: 'After discount: 2000-200=1800. VAT=13% of 1800=234. SP=1800+234=2034',
    misconceptions: {
      A: 'Used a net rate 13%-10%=3% on the marked price (or VAT on the marked price).',
      C: 'Gave the price after discount and forgot to add VAT.',
      D: 'Added VAT to the marked price but forgot the discount.',
    },
  },
  {
    source_ref: 'seed:PCT-2',
    topic: 'PCT',
    stem: 'A radio sold for Rs 1000 gives 25% profit. Find its cost price.',
    option_a: 'Rs 750',
    option_b: 'Rs 1250',
    option_c: 'Rs 250',
    option_d: 'Rs 800',
    correct_option: 'D',
    solution: 'CP=SP*100/(100+25)=1000*100/125=800',
    misconceptions: {
      A: 'Took 25% of the selling price as profit; profit % is on the cost price.',
      B: 'Multiplied SP by 1.25 instead of dividing.',
      C: 'Found only the profit (25% of SP), not the cost price.',
    },
  },
  {
    source_ref: 'seed:INT-1',
    topic: 'INT',
    stem: 'Find the compound amount on Rs 10000 at 10% p.a. for 2 years.',
    option_a: 'Rs 12100',
    option_b: 'Rs 12000',
    option_c: 'Rs 2100',
    option_d: 'Rs 11000',
    correct_option: 'A',
    solution: 'A=P(1+R/100)^T=10000*(1.1)^2=10000*1.21=12100',
    misconceptions: {
      B: 'Used simple interest (Rs 1000 each year).',
      C: 'Found only the compound interest, not the amount.',
      D: 'Calculated for 1 year only.',
    },
  },
  {
    source_ref: 'seed:INT-2',
    topic: 'INT',
    stem: 'A machine worth Rs 50000 depreciates by 20% per year. Find its value after 2 years.',
    option_a: 'Rs 30000',
    option_b: 'Rs 32000',
    option_c: 'Rs 72000',
    option_d: 'Rs 18000',
    correct_option: 'B',
    solution: 'V=P(1-R/100)^T=50000*(0.8)^2=50000*0.64=32000',
    misconceptions: {
      A: 'Used simple depreciation (Rs 10000 each year).',
      C: 'Used the growth formula (1+R/100) instead of (1-R/100).',
      D: 'Found only the total depreciation, not the value.',
    },
  },
  {
    source_ref: 'seed:ALG-1',
    topic: 'ALG',
    stem: 'Simplify: (x^3)^2 * x^-4',
    option_a: 'x',
    option_b: 'x^10',
    option_c: 'x^24',
    option_d: 'x^2',
    correct_option: 'D',
    solution: '(x^3)^2=x^(3*2)=x^6. x^6 * x^-4=x^(6-4)=x^2',
    misconceptions: {
      A: 'Added the powers 3+2 instead of multiplying, then 5-4=1.',
      B: 'Ignored the minus sign in x^-4 and added 6+4.',
      C: 'Multiplied all the powers: 3*2*4.',
    },
  },
  {
    source_ref: 'seed:ALG-2',
    topic: 'ALG',
    stem: 'Solve: x^2-5x+6=0',
    option_a: '-2 and -3',
    option_b: '1 and 6',
    option_c: '2 and 3',
    option_d: '5 and 6',
    correct_option: 'C',
    solution: 'x^2-5x+6=(x-2)(x-3)=0, so x=2 or 3',
    misconceptions: {
      A: 'Sign error: (x+2)(x+3) gives x^2+5x+6, not x^2-5x+6.',
      B: 'Picked factors of 6 without checking that they add to 5.',
      D: 'Read the coefficients 5 and 6 as the roots.',
    },
  },
  {
    source_ref: 'seed:GEO-1',
    topic: 'GEO',
    stem: 'Find the area of a triangle with sides 5 cm, 12 cm and 13 cm.',
    option_a: '60 cm^2',
    option_b: '30 cm^2',
    option_c: '78 cm^2',
    option_d: '900 cm^2',
    correct_option: 'B',
    solution: '5^2+12^2=13^2, so it is right-angled. Area=1/2*5*12=30 cm^2',
    misconceptions: {
      A: 'Forgot the 1/2 in 1/2*base*height.',
      C: 'Used 13 cm (the hypotenuse) as the height with base 12.',
      D: "Used Heron's formula but forgot the square root: 15*10*3*2=900.",
    },
  },
  {
    source_ref: 'seed:GEO-2',
    topic: 'GEO',
    stem: 'Find the volume of a cone of radius 7 cm and height 12 cm. (pi=22/7)',
    option_a: '616 cm^3',
    option_b: '1848 cm^3',
    option_c: '88 cm^3',
    option_d: '2464 cm^3',
    correct_option: 'A',
    solution: 'V=1/3*pi*r^2*h=1/3*22/7*7*7*12=616 cm^3',
    misconceptions: {
      B: 'Forgot the 1/3 and found the volume of a cylinder.',
      C: 'Used r instead of r^2.',
      D: 'Used the diameter 14 cm as the radius.',
    },
  },
  {
    source_ref: 'seed:SET-1',
    topic: 'SET',
    stem: 'In a survey of 100 students, 60 like tea, 50 like coffee and 20 like both. How many like neither?',
    option_a: '90',
    option_b: '30',
    option_c: '70',
    option_d: '10',
    correct_option: 'D',
    solution: 'n(TuC)=60+50-20=90. Neither=100-90=10',
    misconceptions: {
      A: 'Found n(T u C)=90, those who like at least one, not neither.',
      B: 'Left out the 20 who like both: 100-(40+30)=30.',
      C: 'Counted students who like only one drink: 40+30.',
    },
  },
  {
    source_ref: 'seed:SET-2',
    topic: 'SET',
    stem: 'Of 80 people, 50 read paper K, 35 read paper G and 10 read neither. How many read both?',
    option_a: '5',
    option_b: '15',
    option_c: '70',
    option_d: '35',
    correct_option: 'B',
    solution: 'n(KuG)=80-10=70. Both=50+35-70=15',
    misconceptions: {
      A: 'Ignored the 10 who read neither: 50+35-80=5.',
      C: 'Found n(K u G)=70, not those who read both.',
      D: 'Found those who read only K (50-15), not both.',
    },
  },
  {
    source_ref: 'seed:PROB-1',
    topic: 'PROB',
    stem: 'Two fair dice are rolled. Find the probability that the sum is 7.',
    option_a: '1/11',
    option_b: '7/36',
    option_c: '1/6',
    option_d: '1/12',
    correct_option: 'C',
    solution: '36 outcomes. Sum 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1), 6 ways. P=6/36=1/6',
    misconceptions: {
      A: 'Treated the 11 possible sums (2 to 12) as equally likely.',
      B: 'Counted 7 favourable outcomes because the sum is 7.',
      D: 'Counted (1,6),(2,5),(3,4) once each, ignoring order.',
    },
  },
  {
    source_ref: 'seed:PROB-2',
    topic: 'PROB',
    stem: 'A bag has 5 red and 3 blue balls. Two are drawn without replacement. Find P(both red).',
    option_a: '5/14',
    option_b: '25/64',
    option_c: '15/56',
    option_d: '5/8',
    correct_option: 'A',
    solution: 'P=5/8*4/7=20/56=5/14',
    misconceptions: {
      B: 'Treated it as with replacement: 5/8*5/8.',
      C: 'Found P(red then blue): 5/8*3/7.',
      D: 'Found P(red) for the first draw only.',
    },
  },
];

// Science: facts can't be checked by code (CLAUDE.md rule 8), so these seed
// as needs-review until a teacher approves them with `npm run questions:review`.
// Concept questions only (no diagrams). The solution is a short explanation.
const SCIENCE_QUESTIONS = [
  {
    source_ref: 'seed:PHY-1',
    topic: 'PHY',
    stem: 'A girl has a mass of 60 kg on Earth. What is her mass on the Moon?',
    option_a: '10 kg',
    option_b: '600 N',
    option_c: '0 kg',
    option_d: '60 kg',
    correct_option: 'D',
    solution: 'Mass is the amount of matter in a body, so it stays 60 kg anywhere. Only weight (W=mg) changes; on the Moon it is about 1/6 of that on Earth.',
    misconceptions: {
      A: 'Mixed up mass and weight: weight on the Moon is about 1/6, but mass does not change.',
      B: 'Gave her weight on Earth (W=mg=60*10 N). Weight is a force in newtons, not mass.',
      C: 'Thought there is no gravity on the Moon, so nothing has mass there.',
    },
  },
  {
    source_ref: 'seed:PHY-2',
    topic: 'PHY',
    stem: 'Light passes from air into glass. What happens to it?',
    option_a: 'Speeds up',
    option_b: 'Slows down',
    option_c: 'Speed stays same',
    option_d: 'Colour changes',
    correct_option: 'B',
    solution: 'Glass is optically denser than air, so light slows down (to about 2x10^8 m/s) and bends towards the normal. Its colour (frequency) does not change.',
    misconceptions: {
      A: 'Thought light, like sound, travels faster in a denser medium.',
      C: 'Thought light always moves at 3x10^8 m/s; that is its speed in vacuum only.',
      D: 'Thought refraction changes colour. Frequency stays the same; speed and wavelength change.',
    },
  },
  {
    source_ref: 'seed:CHEM-1',
    topic: 'CHEM',
    stem: 'Which gas is given off when zinc reacts with dilute hydrochloric acid?',
    option_a: 'Hydrogen',
    option_b: 'Oxygen',
    option_c: 'Chlorine',
    option_d: 'Carbon dioxide',
    correct_option: 'A',
    solution: 'Zn+2HCl->ZnCl2+H2. A metal and a dilute acid give a salt and hydrogen gas, which burns with a pop sound.',
    misconceptions: {
      B: 'Thought the bubbles must be oxygen, but HCl has no oxygen to give.',
      C: 'Thought the chlorine of HCl is released; it stays in the salt ZnCl2.',
      D: 'Mixed up with acid + carbonate, which gives CO2. Zinc metal has no carbon.',
    },
  },
  {
    source_ref: 'seed:CHEM-2',
    topic: 'CHEM',
    stem: 'An element has atomic number 11. In which group of the periodic table is it?',
    option_a: 'Group 11',
    option_b: 'Group 3',
    option_c: 'Group 1',
    option_d: 'Group 8',
    correct_option: 'C',
    solution: 'Electron configuration 2,8,1: one electron in the outer shell, so group 1 (IA). Its 3 shells give period 3. It is sodium.',
    misconceptions: {
      A: 'Took the atomic number as the group number.',
      B: 'Took the number of shells (3) as the group; shells give the period.',
      D: 'Took the 8 electrons of the second shell, not the outermost shell.',
    },
  },
  {
    source_ref: 'seed:BIO-1',
    topic: 'BIO',
    stem: 'Pure tall (TT) and dwarf (tt) pea plants are crossed. What are the F1 plants?',
    option_a: 'All tall',
    option_b: 'All dwarf',
    option_c: '3 tall:1 dwarf',
    option_d: 'All medium',
    correct_option: 'A',
    solution: 'Every F1 plant is Tt. T (tall) is dominant over t (dwarf), so all F1 plants are tall. The 3:1 ratio appears only in F2.',
    misconceptions: {
      B: 'Mixed up dominant and recessive: t is hidden when T is present.',
      C: 'Gave the F2 ratio (from selfing Tt plants), not F1.',
      D: 'Thought traits blend. Tall is dominant, so Tt plants are fully tall.',
    },
  },
  {
    source_ref: 'seed:BIO-2',
    topic: 'BIO',
    stem: 'Which blood vessel carries oxygen-rich blood from the lungs to the heart?',
    option_a: 'Pulmonary artery',
    option_b: 'Aorta',
    option_c: 'Vena cava',
    option_d: 'Pulmonary vein',
    correct_option: 'D',
    solution: 'The pulmonary vein brings oxygen-rich blood from the lungs to the left atrium. It is the only vein that carries oxygen-rich blood.',
    misconceptions: {
      A: 'Thought arteries always carry oxygen-rich blood. The pulmonary artery takes deoxygenated blood to the lungs.',
      B: 'The aorta carries oxygen-rich blood, but from the heart to the body, not from the lungs.',
      C: 'Thought the vein entering the heart is the vena cava; it brings deoxygenated blood from the body.',
    },
  },
  {
    source_ref: 'seed:EARTH-1',
    topic: 'EARTH',
    stem: 'Which gas from burning fuels is the main cause of global warming?',
    option_a: 'Sulphur dioxide',
    option_b: 'Ozone',
    option_c: 'Carbon dioxide',
    option_d: 'Nitrogen',
    correct_option: 'C',
    solution: 'Burning coal, petrol and wood releases CO2. CO2 traps heat given off by the Earth (greenhouse effect), so the average temperature rises.',
    misconceptions: {
      A: 'Mixed up global warming with acid rain; SO2 causes acid rain.',
      B: 'Mixed up global warming with ozone layer depletion, which is caused by CFCs.',
      D: 'Thought the most plentiful gas in air causes warming; nitrogen does not trap heat.',
    },
  },
  {
    source_ref: 'seed:EARTH-2',
    topic: 'EARTH',
    stem: 'What does a light year measure?',
    option_a: 'Time',
    option_b: 'Distance',
    option_c: 'Speed',
    option_d: 'Brightness',
    correct_option: 'B',
    solution: 'A light year is the distance light travels in one year, about 9.46x10^12 km. It is used to measure distances to stars.',
    misconceptions: {
      A: 'The word "year" made them think it measures time.',
      C: 'Thought it is the speed of light.',
      D: 'The word "light" made them think it measures how bright a star is.',
    },
  },
];

export const SEED_QUESTIONS = [
  ...MATH_QUESTIONS.map((q) => ({ subject: 'MATH', status: 'approved', ...q })),
  ...SCIENCE_QUESTIONS.map((q) => ({ subject: 'SCI', status: 'needs-review', ...q })),
];

// Fake numbers for demos only.
export const DEMO_STUDENTS = [
  { phone: '9800000001', name: 'Aarati Sharma', class: '10' },
  { phone: '9800000002', name: 'Bikash Thapa', class: '10' },
  { phone: '9800000003', name: 'Sita Gurung', class: '10' },
];
